/**
 * 프로젝트 템플릿 선택 및 생성
 */

import { useCallback } from "react";
import { useProjectStore } from "../stores/projectStore";
import { useChapterStore } from "../stores/chapterStore";
import { useUIStore } from "../stores/uiStore";
import {
  LUIE_MANUSCRIPT_DIR,
  LUIE_MANUSCRIPT_README,
  LUIE_PACKAGE_CONTAINER_DIR,
  LUIE_PACKAGE_EXTENSION,
  LUIE_PACKAGE_FORMAT,
  LUIE_PACKAGE_VERSION,
  MARKDOWN_EXTENSION,
  TEXT_EXTENSION,
  DEFAULT_PROJECT_TITLE,
  DEFAULT_NEW_PROJECT_TITLE,
  DEFAULT_CHAPTER_TITLE,
  APP_NAME,
} from "../../../shared/constants";

export function useProjectTemplate(setActiveChapterId: (id: string) => void) {
  const { createProject, setCurrentProject } = useProjectStore();
  const { create: createChapter } = useChapterStore();
  const { setView } = useUIStore();

  const handleSelectProject = useCallback(
    async (templateId: string, projectPath: string) => {
      let projectTitle = DEFAULT_PROJECT_TITLE;

      switch (templateId) {
        case "blank":
          projectTitle = DEFAULT_NEW_PROJECT_TITLE;
          break;
        case "novel_basic":
          projectTitle = "Web Novel";
          break;
        case "script_basic":
          projectTitle = "Screenplay";
          break;
        case "essay":
          projectTitle = "Essay";   
          break;
      }

      const description = `Created with ${templateId} template`;

      const newProject = await createProject(
        projectTitle,
        description,
        projectPath,
      );

      if (newProject) {
        // 파일/패키지 저장
        try {
          const lower = projectPath.toLowerCase();
          const isMarkdown = lower.endsWith(MARKDOWN_EXTENSION);
          const isText = lower.endsWith(TEXT_EXTENSION);
          const isLuiePackage = lower.endsWith(LUIE_PACKAGE_EXTENSION);

          const content = isMarkdown
            ? `# ${newProject.title}\n\n## ${DEFAULT_CHAPTER_TITLE}\n\n`
            : isText
              ? `${newProject.title}\n\n`
              : JSON.stringify(
                  {
                    format: LUIE_PACKAGE_FORMAT,
                    container: LUIE_PACKAGE_CONTAINER_DIR,
                    version: LUIE_PACKAGE_VERSION,
                    projectId: newProject.id,
                    title: newProject.title,
                    templateId,
                    createdAt: newProject.createdAt,
                    updatedAt: newProject.updatedAt,
                  },
                  null,
                  2,
                );

          if (isLuiePackage) {
            // 1) Create package structure
            await window.api.fs.createLuiePackage(projectPath, {
              format: LUIE_PACKAGE_FORMAT,
              container: LUIE_PACKAGE_CONTAINER_DIR,
              version: LUIE_PACKAGE_VERSION,
              projectId: newProject.id,
              title: newProject.title,
              templateId,
              createdAt: newProject.createdAt,
              updatedAt: newProject.updatedAt,
            });

            // 2) Write initial meta.json (already written) + placeholder manuscript index
            await window.api.fs.writeProjectFile(
              projectPath,
              LUIE_MANUSCRIPT_README,
              `# ${newProject.title}\n\nGenerated by ${APP_NAME}.\n`,
            );
          } else {
            await window.api.fs.writeFile(projectPath, content);
          }
        } catch (e) {
          window.api.logger.error("Failed to save project file", e);
        }

        setCurrentProject(newProject);
        const firstChapter = await createChapter({
          projectId: newProject.id,
          title: DEFAULT_CHAPTER_TITLE,
        });

        // If this is a .luie package, also persist chapter content into the package
        if (firstChapter?.id && projectPath.toLowerCase().endsWith(LUIE_PACKAGE_EXTENSION)) {
          try {
            await window.api.fs.writeProjectFile(
              projectPath,
              `${LUIE_MANUSCRIPT_DIR}/${firstChapter.id}${MARKDOWN_EXTENSION}`,
              "",
            );
          } catch (e) {
            window.api.logger.warn("Failed to write initial chapter file", e);
          }
        }

        if (firstChapter?.id) {
          setActiveChapterId(firstChapter.id);
        }
        setView("editor");

        try {
          await window.api.window.toggleFullscreen();
        } catch (e) {
          window.api.logger.error("Failed to maximize window", e);
        }
      }
    },
    [createProject, setCurrentProject, createChapter, setView, setActiveChapterId],
  );

  return { handleSelectProject };
}
