allowBuilds:
  '@google/genai': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
patchedDependencies:
  better-sqlite3: patches/better-sqlite3.patch
