import type { ShortcutAction } from "../types/index.js";

export const SHORTCUT_ACTIONS: Array<{ id: ShortcutAction; labelKey: string }> = [
  { id: "app.openSettings", labelKey: "settings.shortcuts.openSettings" },
  { id: "app.closeWindow", labelKey: "settings.shortcuts.closeWindow" },
  { id: "app.quit", labelKey: "settings.shortcuts.quitApp" },

  { id: "chapter.new", labelKey: "settings.shortcuts.newChapter" },
  { id: "chapter.save", labelKey: "settings.shortcuts.saveChapter" },
  { id: "chapter.delete", labelKey: "settings.shortcuts.deleteChapter" },
  { id: "chapter.open.1", labelKey: "settings.shortcuts.openChapter1" },
  { id: "chapter.open.2", labelKey: "settings.shortcuts.openChapter2" },
  { id: "chapter.open.3", labelKey: "settings.shortcuts.openChapter3" },
  { id: "chapter.open.4", labelKey: "settings.shortcuts.openChapter4" },
  { id: "chapter.open.5", labelKey: "settings.shortcuts.openChapter5" },
  { id: "chapter.open.6", labelKey: "settings.shortcuts.openChapter6" },
  { id: "chapter.open.7", labelKey: "settings.shortcuts.openChapter7" },
  { id: "chapter.open.8", labelKey: "settings.shortcuts.openChapter8" },
  { id: "chapter.open.9", labelKey: "settings.shortcuts.openChapter9" },
  { id: "chapter.open.0", labelKey: "settings.shortcuts.openChapter10" },

  { id: "view.toggleSidebar", labelKey: "settings.shortcuts.toggleSidebar" },
  { id: "view.sidebar.open", labelKey: "settings.shortcuts.openSidebar" },
  { id: "view.sidebar.close", labelKey: "settings.shortcuts.closeSidebar" },
  { id: "view.toggleContextPanel", labelKey: "settings.shortcuts.toggleContext" },
  { id: "view.context.open", labelKey: "settings.shortcuts.openContext" },
  { id: "view.context.close", labelKey: "settings.shortcuts.closeContext" },
  { id: "sidebar.section.manuscript.toggle", labelKey: "settings.shortcuts.toggleBinder" },
  { id: "sidebar.section.snapshot.open", labelKey: "settings.shortcuts.openSnapshotSection" },
  { id: "sidebar.section.trash.open", labelKey: "settings.shortcuts.openTrashSection" },
  { id: "project.rename", labelKey: "settings.shortcuts.renameProject" },

  { id: "research.open.character", labelKey: "settings.shortcuts.openCharacter" },
  { id: "research.open.world", labelKey: "settings.shortcuts.openWorld" },
  { id: "research.open.scrap", labelKey: "settings.shortcuts.openScrap" },
  { id: "research.open.analysis", labelKey: "settings.shortcuts.openAnalysis" },
  { id: "research.open.character.left", labelKey: "settings.shortcuts.openCharacterLeft" },
  { id: "research.open.world.left", labelKey: "settings.shortcuts.openWorldLeft" },
  { id: "research.open.scrap.left", labelKey: "settings.shortcuts.openScrapLeft" },
  { id: "research.open.analysis.left", labelKey: "settings.shortcuts.openAnalysisLeft" },
  { id: "character.openTemplate", labelKey: "settings.shortcuts.openCharacterTemplate" },

  { id: "world.tab.synopsis", labelKey: "settings.shortcuts.worldTabSynopsis" },
  { id: "world.tab.terms", labelKey: "settings.shortcuts.worldTabTerms" },
  { id: "world.tab.mindmap", labelKey: "settings.shortcuts.worldTabMindmap" },
  { id: "world.tab.drawing", labelKey: "settings.shortcuts.worldTabDrawing" },
  { id: "world.tab.plot", labelKey: "settings.shortcuts.worldTabPlot" },
  { id: "world.addTerm", labelKey: "settings.shortcuts.addWorldTerm" },
  { id: "scrap.addMemo", labelKey: "settings.shortcuts.addScrapMemo" },

  { id: "export.openPreview", labelKey: "settings.shortcuts.openExportPreview" },
  { id: "export.openWindow", labelKey: "settings.shortcuts.openExportWindow" },
  { id: "editor.openRight", labelKey: "settings.shortcuts.openEditorRight" },
  { id: "editor.openLeft", labelKey: "settings.shortcuts.openEditorLeft" },
  { id: "split.swapSides", labelKey: "settings.shortcuts.swapSplitSides" },
  { id: "editor.fontSize.increase", labelKey: "settings.shortcuts.editorFontIncrease" },
  { id: "editor.fontSize.decrease", labelKey: "settings.shortcuts.editorFontDecrease" },
  { id: "window.toggleFullscreen", labelKey: "settings.shortcuts.toggleFullscreen" },
];


