export const PACKAGED_SCHEMA_REQUIRED_COLUMNS: Readonly<Record<string, ReadonlyArray<string>>> = {
  // `projectPath` stays as a legacy compatibility column for now, but it is not
  // a required canonical project field for bootstrap integrity checks.
  Project: ["id", "title"],
  ProjectAttachment: ["projectId", "projectPath"],
  ProjectLocalState: ["projectId", "lastOpenedAt"],
  ProjectSettings: [
    "id",
    "projectId",
    "autoSave",
    "autoSaveInterval",
    "llmModelPath",
    "llmEmbeddingModelPath",
    "llmEmbeddingDimension",
    "llmProviderHint",
  ],
  Chapter: ["id", "projectId", "order", "wordCount", "deletedAt"],
  Scene: ["id", "projectId", "chapterId", "title", "body", "order", "deletedAt"],
  ChapterBody: ["chapterId", "content", "contentHash", "updatedAt"],
  ChapterRevision: ["id", "chapterId", "contentHash", "content", "reason"],
  SearchDirtyQueue: [
    "id",
    "projectId",
    "sourceType",
    "sourceId",
    "reason",
    "status",
    "attempts",
  ],
  MemoryChunk: [
    "id",
    "projectId",
    "sourceType",
    "sourceId",
    "chunkIndex",
    "content",
    "contentHash",
    "indexText",
    "indexTextHash",
    "contextLabel",
    "sourceContentHash",
    "paragraphStartIndex",
    "paragraphEndIndex",
    "sceneId",
  ],
  MemoryBuildJob: [
    "id",
    "projectId",
    "targetType",
    "targetId",
    "jobType",
    "status",
    "priority",
  ],
  MemoryEmbedding: [
    "id",
    "chunkId",
    "projectId",
    "contentHash",
    "vec",
    "dimension",
  ],
  ChapterSummary: [
    "id",
    "projectId",
    "chapterId",
    "chapterNumber",
    "summary",
    "contentHash",
    "isFallback",
    "model",
    "generatedAt",
  ],
  MemoryEvalCase: ["id", "projectId", "name", "question", "caseType", "severity"],
  MemoryEvalEvidence: [
    "id",
    "caseId",
    "projectId",
    "chapterId",
    "expectedChunkId",
    "startOffset",
    "endOffset",
    "quote",
  ],
  MemoryEvalEntity: ["id", "caseId", "projectId", "name", "entityType"],
  MemoryEvalRelation: ["id", "caseId", "projectId", "sourceName", "targetName", "relation"],
  MemoryEvalRun: ["id", "projectId", "label", "engineVersion", "status", "startedAt"],
  MemoryEvalResult: [
    "id",
    "runId",
    "caseId",
    "projectId",
    "groundingStatus",
    "evidenceHitCount",
    "evidenceMissCount",
    "contextRecallAtK",
    "p0FailureCount",
    "p0Failures",
  ],
  MemoryEvalFeedback: [
    "id",
    "projectId",
    "feedbackKind",
    "question",
    "evidenceJson",
    "status",
  ],
  MemoryEntity: [
    "id",
    "projectId",
    "entityType",
    "canonicalName",
    "status",
    "confidence",
    "createdBy",
    "updatedAt",
    "deletedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryEntityAlias: [
    "id",
    "projectId",
    "entityId",
    "entityType",
    "alias",
    "normalizedAlias",
    "status",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryEntityMention: [
    "id",
    "projectId",
    "entityId",
    "aliasId",
    "chapterId",
    "chunkId",
    "contentHash",
    "sourceContentHash",
    "startOffset",
    "endOffset",
    "quote",
    "extractorVersion",
    "confidence",
    "status",
    "createdAt",
    "updatedAt",
  ],
  MemoryEntityMergeAudit: [
    "id",
    "projectId",
    "sourceEntityId",
    "targetEntityId",
    "aliasId",
    "action",
    "reason",
    "createdBy",
    "createdAt",
    "updatedAt",
  ],
  MemoryEpisodeExtractionJob: [
    "id",
    "projectId",
    "sourceType",
    "sourceId",
    "sourceContentHash",
    "extractorVersion",
    "status",
    "priority",
    "attempts",
    "error",
    "createdAt",
    "updatedAt",
  ],
  MemoryEpisode: [
    "id",
    "projectId",
    "sourceType",
    "sourceId",
    "chapterId",
    "sceneId",
    "sourceContentHash",
    "extractorVersion",
    "episodeType",
    "title",
    "summary",
    "status",
    "confidence",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryEpisodeParticipant: [
    "id",
    "projectId",
    "episodeId",
    "entityId",
    "surfaceName",
    "role",
    "status",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryEpisodeEvidence: [
    "id",
    "projectId",
    "episodeId",
    "chapterId",
    "chunkId",
    "contentHash",
    "sourceContentHash",
    "startOffset",
    "endOffset",
    "quote",
  ],
  MemoryStateChangeCandidate: [
    "id",
    "projectId",
    "episodeId",
    "evidenceId",
    "subjectEntityId",
    "stateType",
    "beforeValue",
    "afterValue",
    "status",
    "confidence",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryFact: [
    "id",
    "projectId",
    "subjectEntityId",
    "predicate",
    "objectEntityId",
    "objectValue",
    "valueType",
    "validFromChapterId",
    "validFromChapterOrder",
    "validToChapterId",
    "validToChapterOrder",
    "observedAtChapterId",
    "observedAtChapterOrder",
    "confidence",
    "status",
    "provenanceKind",
    "canonStatus",
    "extractorVersion",
    "sourceContentHash",
    "invalidatedByFactId",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryFactEvidence: ["id", "projectId", "factId", "evidenceId", "createdAt", "updatedAt"],
  MemoryFactInvalidation: [
    "id",
    "projectId",
    "invalidatedFactId",
    "invalidatingFactId",
    "reason",
    "reviewStatus",
    "reviewerNote",
    "reviewedAt",
    "createdAt",
    "updatedAt",
  ],
  MemoryRelationState: [
    "id",
    "projectId",
    "factId",
    "sourceEntityId",
    "targetEntityId",
    "relation",
    "createdAt",
    "updatedAt",
  ],
  MemoryCharacterState: [
    "id",
    "projectId",
    "factId",
    "entityId",
    "stateType",
    "stateValue",
    "createdAt",
    "updatedAt",
  ],
  MemoryKnowledgeState: [
    "id",
    "projectId",
    "factId",
    "knowerEntityId",
    "secretEntityId",
    "knowledgeKey",
    "knowledgeValue",
    "createdAt",
    "updatedAt",
  ],
  MemoryNarrativeSummary: [
    "id",
    "projectId",
    "summaryType",
    "scopeType",
    "scopeId",
    "title",
    "summary",
    "status",
    "confidence",
    "extractorVersion",
    "sourceContentHash",
    "generatedAt",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryNarrativeSummarySource: [
    "id",
    "projectId",
    "summaryId",
    "sourceType",
    "episodeId",
    "factId",
    "chunkId",
    "chapterSummaryId",
    "quote",
    "contentHash",
    "createdAt",
    "updatedAt",
  ],
  Note: ["id", "projectId", "title", "body", "deletedAt"],
  Synopsis: ["id", "projectId", "title", "body", "deletedAt"],
  Plot: ["id", "projectId", "title", "body", "deletedAt"],
  Character: ["id", "projectId", "firstAppearance", "attributes", "deletedAt"],
  Event: ["id", "projectId", "name", "deletedAt"],
  Faction: ["id", "projectId", "name", "deletedAt"],
  WorldDocument: ["id", "projectId", "docType", "payload"],
  ScrapMemo: ["id", "projectId", "title", "content", "tags", "sortOrder", "updatedAt", "deletedAt"],
  Term: ["id", "projectId", "term", "order", "deletedAt"],
  Snapshot: ["id", "projectId", "content", "contentLength", "type"],
  WorldEntity: ["id", "projectId", "type", "name", "positionX", "positionY", "memoryEntityId", "deletedAt"],
  EntityRelation: ["id", "projectId", "sourceId", "targetId", "relation"],
};
