export const PACKAGED_SCHEMA_REQUIRED_TABLES = [
  "Project",
  "ProjectAttachment",
  "ProjectLocalState",
  "ProjectSettings",
  "Chapter",
  "Scene",
  "ChapterBody",
  "ChapterRevision",
  "SearchDirtyQueue",
  "MemoryChunk",
  "MemoryBuildJob",
  "MemoryEmbedding",
  "ChapterSummary",
  "MemoryEvalCase",
  "MemoryEvalEvidence",
  "MemoryEvalEntity",
  "MemoryEvalRelation",
  "MemoryEvalRun",
  "MemoryEvalResult",
  "MemoryEntity",
  "MemoryEntityAlias",
  "MemoryEntityMention",
  "MemoryEpisodeExtractionJob",
  "MemoryEpisode",
  "MemoryEpisodeParticipant",
  "MemoryEpisodeEvidence",
  "MemoryStateChangeCandidate",
  "MemoryFact",
  "MemoryFactEvidence",
  "MemoryFactInvalidation",
  "MemoryRelationState",
  "MemoryCharacterState",
  "MemoryKnowledgeState",
  "MemoryNarrativeSummary",
  "MemoryNarrativeSummarySource",
  "Note",
  "Synopsis",
  "Plot",
  "Character",
  "Event",
  "Faction",
  "WorldDocument",
  "ScrapMemo",
  "Term",
  "Snapshot",
  "WorldEntity",
  "EntityRelation",
] as const;

type ColumnPatch = {
  table: string;
  column: string;
  sql: string;
};

type IndexPatch = {
  name: string;
  table: string;
  sql: string;
};

export const PACKAGED_SCHEMA_COLUMN_PATCHES: ReadonlyArray<ColumnPatch> = [
  {
    table: "Term",
    column: "order",
    sql: 'ALTER TABLE "Term" ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;',
  },
  {
    table: "Snapshot",
    column: "contentLength",
    sql: 'ALTER TABLE "Snapshot" ADD COLUMN "contentLength" INTEGER NOT NULL DEFAULT 0;',
  },
  {
    table: "Snapshot",
    column: "description",
    sql: 'ALTER TABLE "Snapshot" ADD COLUMN "description" TEXT;',
  },
  {
    table: "Project",
    column: "projectPath",
    sql: 'ALTER TABLE "Project" ADD COLUMN "projectPath" TEXT;',
  },
  {
    table: "Chapter",
    column: "synopsis",
    sql: 'ALTER TABLE "Chapter" ADD COLUMN "synopsis" TEXT;',
  },
  {
    table: "MemoryChunk",
    column: "sceneId",
    sql: 'ALTER TABLE "MemoryChunk" ADD COLUMN "sceneId" TEXT;',
  },
  {
    table: "MemoryChunk",
    column: "indexText",
    sql: 'ALTER TABLE "MemoryChunk" ADD COLUMN "indexText" TEXT NOT NULL DEFAULT \'\';',
  },
  {
    table: "MemoryChunk",
    column: "indexTextHash",
    sql: 'ALTER TABLE "MemoryChunk" ADD COLUMN "indexTextHash" TEXT NOT NULL DEFAULT \'\';',
  },
  {
    table: "MemoryChunk",
    column: "contextLabel",
    sql: 'ALTER TABLE "MemoryChunk" ADD COLUMN "contextLabel" TEXT;',
  },
  {
    table: "MemoryChunk",
    column: "sourceContentHash",
    sql: 'ALTER TABLE "MemoryChunk" ADD COLUMN "sourceContentHash" TEXT NOT NULL DEFAULT \'\';',
  },
  {
    table: "Chapter",
    column: "wordCount",
    sql: 'ALTER TABLE "Chapter" ADD COLUMN "wordCount" INTEGER NOT NULL DEFAULT 0;',
  },
  {
    table: "Chapter",
    column: "deletedAt",
    sql: 'ALTER TABLE "Chapter" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "Character",
    column: "deletedAt",
    sql: 'ALTER TABLE "Character" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "Character",
    column: "firstAppearance",
    sql: 'ALTER TABLE "Character" ADD COLUMN "firstAppearance" TEXT;',
  },
  {
    table: "Character",
    column: "attributes",
    sql: 'ALTER TABLE "Character" ADD COLUMN "attributes" TEXT;',
  },
  {
    table: "Event",
    column: "deletedAt",
    sql: 'ALTER TABLE "Event" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "Faction",
    column: "deletedAt",
    sql: 'ALTER TABLE "Faction" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "Term",
    column: "deletedAt",
    sql: 'ALTER TABLE "Term" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "WorldEntity",
    column: "deletedAt",
    sql: 'ALTER TABLE "WorldEntity" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "Scene",
    column: "deletedAt",
    sql: 'ALTER TABLE "Scene" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "Note",
    column: "deletedAt",
    sql: 'ALTER TABLE "Note" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "Synopsis",
    column: "deletedAt",
    sql: 'ALTER TABLE "Synopsis" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "Plot",
    column: "deletedAt",
    sql: 'ALTER TABLE "Plot" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "ScrapMemo",
    column: "deletedAt",
    sql: 'ALTER TABLE "ScrapMemo" ADD COLUMN "deletedAt" DATETIME;',
  },
  {
    table: "ProjectSettings",
    column: "llmModelPath",
    sql: 'ALTER TABLE "ProjectSettings" ADD COLUMN "llmModelPath" TEXT;',
  },
  {
    table: "ProjectSettings",
    column: "llmEmbeddingModelPath",
    sql: 'ALTER TABLE "ProjectSettings" ADD COLUMN "llmEmbeddingModelPath" TEXT;',
  },
  {
    table: "ProjectSettings",
    column: "llmEmbeddingDimension",
    sql: 'ALTER TABLE "ProjectSettings" ADD COLUMN "llmEmbeddingDimension" INTEGER NOT NULL DEFAULT 1024;',
  },
  {
    table: "ProjectSettings",
    column: "llmProviderHint",
    sql: 'ALTER TABLE "ProjectSettings" ADD COLUMN "llmProviderHint" TEXT;',
  },
  {
    table: "ChapterSummary",
    column: "contentHash",
    sql: "ALTER TABLE \"ChapterSummary\" ADD COLUMN \"contentHash\" TEXT NOT NULL DEFAULT '';",
  },
];

export const PACKAGED_SCHEMA_INDEX_PATCHES: ReadonlyArray<IndexPatch> = [
  {
    name: "Character_projectId_createdAt_idx",
    table: "Character",
    sql: 'CREATE INDEX IF NOT EXISTS "Character_projectId_createdAt_idx" ON "Character"("projectId", "createdAt");',
  },
  {
    name: "Event_projectId_createdAt_idx",
    table: "Event",
    sql: 'CREATE INDEX IF NOT EXISTS "Event_projectId_createdAt_idx" ON "Event"("projectId", "createdAt");',
  },
  {
    name: "Faction_projectId_createdAt_idx",
    table: "Faction",
    sql: 'CREATE INDEX IF NOT EXISTS "Faction_projectId_createdAt_idx" ON "Faction"("projectId", "createdAt");',
  },
  {
    name: "Term_projectId_createdAt_idx",
    table: "Term",
    sql: 'CREATE INDEX IF NOT EXISTS "Term_projectId_createdAt_idx" ON "Term"("projectId", "createdAt");',
  },
  {
    name: "WorldEntity_projectId_createdAt_idx",
    table: "WorldEntity",
    sql: 'CREATE INDEX IF NOT EXISTS "WorldEntity_projectId_createdAt_idx" ON "WorldEntity"("projectId", "createdAt");',
  },
  {
    name: "ScrapMemo_projectId_sortOrder_updatedAt_idx",
    table: "ScrapMemo",
    sql: 'CREATE INDEX IF NOT EXISTS "ScrapMemo_projectId_sortOrder_updatedAt_idx" ON "ScrapMemo"("projectId", "sortOrder", "updatedAt");',
  },
  {
    name: "MemoryChunkFts",
    table: "MemoryChunk",
    sql: `CREATE VIRTUAL TABLE IF NOT EXISTS "MemoryChunkFts"
USING fts5(
    "chunkId" UNINDEXED,
    "projectId" UNINDEXED,
    "chapterId" UNINDEXED,
    "content",
    tokenize = 'trigram'
);`,
  },
  {
    name: "MemoryChunk_projectId_sceneId_idx",
    table: "MemoryChunk",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryChunk_projectId_sceneId_idx" ON "MemoryChunk"("projectId", "sceneId");',
  },
  {
    name: "MemoryChunk_id_projectId_key",
    table: "MemoryChunk",
    sql: 'CREATE UNIQUE INDEX IF NOT EXISTS "MemoryChunk_id_projectId_key" ON "MemoryChunk"("id", "projectId");',
  },
  {
    name: "ChapterSummary_id_projectId_key",
    table: "ChapterSummary",
    sql: 'CREATE UNIQUE INDEX IF NOT EXISTS "ChapterSummary_id_projectId_key" ON "ChapterSummary"("id", "projectId");',
  },
  {
    name: "MemoryEpisode_id_projectId_key",
    table: "MemoryEpisode",
    sql: 'CREATE UNIQUE INDEX IF NOT EXISTS "MemoryEpisode_id_projectId_key" ON "MemoryEpisode"("id", "projectId");',
  },
  {
    name: "MemoryEntity_id_projectId_key",
    table: "MemoryEntity",
    sql: 'CREATE UNIQUE INDEX IF NOT EXISTS "MemoryEntity_id_projectId_key" ON "MemoryEntity"("id", "projectId");',
  },
  {
    name: "MemoryEpisodeEvidence_id_projectId_key",
    table: "MemoryEpisodeEvidence",
    sql: 'CREATE UNIQUE INDEX IF NOT EXISTS "MemoryEpisodeEvidence_id_projectId_key" ON "MemoryEpisodeEvidence"("id", "projectId");',
  },
  {
    name: "MemoryFact_projectId_subject_predicate_idx",
    table: "MemoryFact",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryFact_projectId_subject_predicate_idx" ON "MemoryFact"("projectId", "subjectEntityId", "predicate");',
  },
  {
    name: "MemoryFact_projectId_validity_idx",
    table: "MemoryFact",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryFact_projectId_validity_idx" ON "MemoryFact"("projectId", "validFromChapterOrder", "validToChapterOrder");',
  },
  {
    name: "MemoryFact_projectId_status_idx",
    table: "MemoryFact",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryFact_projectId_status_idx" ON "MemoryFact"("projectId", "status");',
  },
  {
    name: "MemoryFact_id_projectId_key",
    table: "MemoryFact",
    sql: 'CREATE UNIQUE INDEX IF NOT EXISTS "MemoryFact_id_projectId_key" ON "MemoryFact"("id", "projectId");',
  },
  {
    name: "MemoryFactEvidence_factId_idx",
    table: "MemoryFactEvidence",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryFactEvidence_factId_idx" ON "MemoryFactEvidence"("factId");',
  },
  {
    name: "MemoryFactInvalidation_invalidatedFactId_idx",
    table: "MemoryFactInvalidation",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryFactInvalidation_invalidatedFactId_idx" ON "MemoryFactInvalidation"("invalidatedFactId");',
  },
  {
    name: "MemoryRelationState_projectId_relation_idx",
    table: "MemoryRelationState",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryRelationState_projectId_relation_idx" ON "MemoryRelationState"("projectId", "relation");',
  },
  {
    name: "MemoryCharacterState_projectId_stateType_idx",
    table: "MemoryCharacterState",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryCharacterState_projectId_stateType_idx" ON "MemoryCharacterState"("projectId", "stateType");',
  },
  {
    name: "MemoryKnowledgeState_projectId_knower_idx",
    table: "MemoryKnowledgeState",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryKnowledgeState_projectId_knower_idx" ON "MemoryKnowledgeState"("projectId", "knowerEntityId");',
  },
  {
    name: "MemoryNarrativeSummary_projectId_type_idx",
    table: "MemoryNarrativeSummary",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryNarrativeSummary_projectId_type_idx" ON "MemoryNarrativeSummary"("projectId", "summaryType");',
  },
  {
    name: "MemoryNarrativeSummary_projectId_scope_idx",
    table: "MemoryNarrativeSummary",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryNarrativeSummary_projectId_scope_idx" ON "MemoryNarrativeSummary"("projectId", "scopeType", "scopeId");',
  },
  {
    name: "MemoryNarrativeSummary_projectId_status_idx",
    table: "MemoryNarrativeSummary",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryNarrativeSummary_projectId_status_idx" ON "MemoryNarrativeSummary"("projectId", "status");',
  },
  {
    name: "MemoryNarrativeSummary_id_projectId_key",
    table: "MemoryNarrativeSummary",
    sql: 'CREATE UNIQUE INDEX IF NOT EXISTS "MemoryNarrativeSummary_id_projectId_key" ON "MemoryNarrativeSummary"("id", "projectId");',
  },
  {
    name: "MemoryNarrativeSummarySource_summaryId_idx",
    table: "MemoryNarrativeSummarySource",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryNarrativeSummarySource_summaryId_idx" ON "MemoryNarrativeSummarySource"("summaryId");',
  },
  {
    name: "MemoryNarrativeSummarySource_projectId_sourceType_idx",
    table: "MemoryNarrativeSummarySource",
    sql: 'CREATE INDEX IF NOT EXISTS "MemoryNarrativeSummarySource_projectId_sourceType_idx" ON "MemoryNarrativeSummarySource"("projectId", "sourceType");',
  },
];

export const PACKAGED_SCHEMA_REQUIRED_COLUMNS: Readonly<Record<string, ReadonlyArray<string>>> = {
  // `projectPath` stays as a legacy compatibility column for now, but it is not
  // a required canonical project field for bootstrap integrity checks.
  Project: ["id", "title"],
  ProjectAttachment: ["projectId", "projectPath"],
  ProjectLocalState: ["projectId", "lastOpenedAt"],
  ProjectSettings: [
    "id",
    "projectId",
    "autoSave",
    "autoSaveInterval",
    "llmModelPath",
    "llmEmbeddingModelPath",
    "llmEmbeddingDimension",
    "llmProviderHint",
  ],
  Chapter: ["id", "projectId", "order", "wordCount", "deletedAt"],
  Scene: ["id", "projectId", "chapterId", "title", "body", "order", "deletedAt"],
  ChapterBody: ["chapterId", "content", "contentHash", "updatedAt"],
  ChapterRevision: ["id", "chapterId", "contentHash", "content", "reason"],
  SearchDirtyQueue: [
    "id",
    "projectId",
    "sourceType",
    "sourceId",
    "reason",
    "status",
    "attempts",
  ],
  MemoryChunk: [
    "id",
    "projectId",
    "sourceType",
    "sourceId",
    "chunkIndex",
    "content",
    "contentHash",
    "indexText",
    "indexTextHash",
    "contextLabel",
    "sourceContentHash",
    "sceneId",
  ],
  MemoryBuildJob: [
    "id",
    "projectId",
    "targetType",
    "targetId",
    "jobType",
    "status",
    "priority",
  ],
  MemoryEmbedding: [
    "id",
    "chunkId",
    "projectId",
    "contentHash",
    "vec",
    "dimension",
  ],
  ChapterSummary: [
    "id",
    "projectId",
    "chapterId",
    "chapterNumber",
    "summary",
    "contentHash",
    "isFallback",
    "model",
    "generatedAt",
  ],
  MemoryEvalCase: ["id", "projectId", "name", "question", "caseType", "severity"],
  MemoryEvalEvidence: [
    "id",
    "caseId",
    "projectId",
    "chapterId",
    "expectedChunkId",
    "startOffset",
    "endOffset",
    "quote",
  ],
  MemoryEvalEntity: ["id", "caseId", "projectId", "name", "entityType"],
  MemoryEvalRelation: ["id", "caseId", "projectId", "sourceName", "targetName", "relation"],
  MemoryEvalRun: ["id", "projectId", "label", "engineVersion", "status", "startedAt"],
  MemoryEvalResult: [
    "id",
    "runId",
    "caseId",
    "projectId",
    "groundingStatus",
    "evidenceHitCount",
    "evidenceMissCount",
    "contextRecallAtK",
    "p0FailureCount",
    "p0Failures",
  ],
  MemoryEntity: [
    "id",
    "projectId",
    "entityType",
    "canonicalName",
    "status",
    "confidence",
    "createdBy",
    "updatedAt",
    "deletedAt",
  ],
  MemoryEntityAlias: [
    "id",
    "projectId",
    "entityId",
    "entityType",
    "alias",
    "normalizedAlias",
    "status",
    "createdAt",
    "updatedAt",
  ],
  MemoryEntityMention: [
    "id",
    "projectId",
    "entityId",
    "aliasId",
    "chapterId",
    "chunkId",
    "contentHash",
    "sourceContentHash",
    "startOffset",
    "endOffset",
    "quote",
    "extractorVersion",
    "confidence",
    "status",
    "createdAt",
    "updatedAt",
  ],
  MemoryEpisodeExtractionJob: [
    "id",
    "projectId",
    "sourceType",
    "sourceId",
    "sourceContentHash",
    "extractorVersion",
    "status",
    "priority",
    "attempts",
    "error",
    "createdAt",
    "updatedAt",
  ],
  MemoryEpisode: [
    "id",
    "projectId",
    "sourceType",
    "sourceId",
    "chapterId",
    "sceneId",
    "sourceContentHash",
    "extractorVersion",
    "episodeType",
    "title",
    "summary",
    "status",
    "confidence",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryEpisodeParticipant: [
    "id",
    "projectId",
    "episodeId",
    "entityId",
    "surfaceName",
    "role",
    "status",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryEpisodeEvidence: [
    "id",
    "projectId",
    "episodeId",
    "chapterId",
    "chunkId",
    "contentHash",
    "sourceContentHash",
    "startOffset",
    "endOffset",
    "quote",
  ],
  MemoryStateChangeCandidate: [
    "id",
    "projectId",
    "episodeId",
    "evidenceId",
    "subjectEntityId",
    "stateType",
    "beforeValue",
    "afterValue",
    "status",
    "confidence",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryFact: [
    "id",
    "projectId",
    "subjectEntityId",
    "predicate",
    "objectEntityId",
    "objectValue",
    "valueType",
    "validFromChapterId",
    "validFromChapterOrder",
    "validToChapterId",
    "validToChapterOrder",
    "observedAtChapterId",
    "observedAtChapterOrder",
    "confidence",
    "status",
    "extractorVersion",
    "sourceContentHash",
    "invalidatedByFactId",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryFactEvidence: ["id", "projectId", "factId", "evidenceId", "createdAt", "updatedAt"],
  MemoryFactInvalidation: [
    "id",
    "projectId",
    "invalidatedFactId",
    "invalidatingFactId",
    "reason",
    "createdAt",
    "updatedAt",
  ],
  MemoryRelationState: [
    "id",
    "projectId",
    "factId",
    "sourceEntityId",
    "targetEntityId",
    "relation",
    "createdAt",
    "updatedAt",
  ],
  MemoryCharacterState: [
    "id",
    "projectId",
    "factId",
    "entityId",
    "stateType",
    "stateValue",
    "createdAt",
    "updatedAt",
  ],
  MemoryKnowledgeState: [
    "id",
    "projectId",
    "factId",
    "knowerEntityId",
    "secretEntityId",
    "knowledgeKey",
    "knowledgeValue",
    "createdAt",
    "updatedAt",
  ],
  MemoryNarrativeSummary: [
    "id",
    "projectId",
    "summaryType",
    "scopeType",
    "scopeId",
    "title",
    "summary",
    "status",
    "confidence",
    "extractorVersion",
    "sourceContentHash",
    "generatedAt",
    "createdAt",
    "updatedAt",
    "rejectedAt",
    "rejectionReason",
  ],
  MemoryNarrativeSummarySource: [
    "id",
    "projectId",
    "summaryId",
    "sourceType",
    "episodeId",
    "factId",
    "chunkId",
    "chapterSummaryId",
    "quote",
    "contentHash",
    "createdAt",
    "updatedAt",
  ],
  Note: ["id", "projectId", "title", "body", "deletedAt"],
  Synopsis: ["id", "projectId", "title", "body", "deletedAt"],
  Plot: ["id", "projectId", "title", "body", "deletedAt"],
  Character: ["id", "projectId", "firstAppearance", "attributes", "deletedAt"],
  Event: ["id", "projectId", "name", "deletedAt"],
  Faction: ["id", "projectId", "name", "deletedAt"],
  WorldDocument: ["id", "projectId", "docType", "payload"],
  ScrapMemo: ["id", "projectId", "title", "content", "tags", "sortOrder", "updatedAt", "deletedAt"],
  Term: ["id", "projectId", "term", "order", "deletedAt"],
  Snapshot: ["id", "projectId", "content", "contentLength", "type"],
  WorldEntity: ["id", "projectId", "type", "name", "positionX", "positionY", "deletedAt"],
  EntityRelation: ["id", "projectId", "sourceId", "targetId", "relation"],
};
