export const LLM_DEFAULT_GPU_LAYERS = 999;
export const LLM_DEFAULT_CONTEXT_SIZE = 4_096;
export const LLM_DEFAULT_IDLE_UNLOAD_MS = 2 * 60 * 1000;
export const LLAMA_SERVER_DEFAULT_IDLE_TIMEOUT_MS = 2 * 60 * 1000;
export const LLAMA_SERVER_DEFAULT_PARALLEL = 1;
