export const LLM_DEFAULT_GPU_LAYERS = 999;
export const LLM_DEFAULT_CONTEXT_SIZE = 8_192;
export const LLM_DEFAULT_IDLE_UNLOAD_MS = 10 * 60 * 1000;
export const LLAMA_SERVER_DEFAULT_IDLE_TIMEOUT_MS = 5 * 60 * 1000;
export const LLAMA_SERVER_DEFAULT_PARALLEL = 1;

