export const AUTO_SAVE_INTERVAL = 30000;
export const DEFAULT_AUTO_SAVE_INTERVAL_MS = AUTO_SAVE_INTERVAL;
export const DEFAULT_AUTO_SAVE_DEBOUNCE_MS = 1000;
export const DEFAULT_PROJECT_AUTO_SAVE_INTERVAL_SECONDS = 30;
export const DEFAULT_AUTO_SAVE_ENABLED = true;
export const AUTO_SAVE_STALE_THRESHOLD_MS = 5 * 60 * 1000;
export const AUTO_SAVE_CLEANUP_INTERVAL_MS = 60 * 1000;

export const EMERGENCY_SNAPSHOT_MAX_LENGTH = 200;
export const EMERGENCY_SNAPSHOT_INTERVAL_MS = 5_000;
