export const SNAPSHOT_INTERVAL_MS = 60 * 1000;
export const SNAPSHOT_KEEP_COUNT = 2000;
export const SNAPSHOT_FILE_KEEP_COUNT = 50;
export const DEFAULT_PROJECT_SNAPSHOT_KEEP_COUNT = 2000;
export const SNAPSHOT_MIN_CONTENT_LENGTH = 1;
export const SNAPSHOT_MIN_CHANGE_RATIO = 0.0;
export const SNAPSHOT_MIN_CHANGE_ABSOLUTE = 30;
