/**
 * Shared type definitions
 */

export type {
  Project,
  ProjectAttachmentStatus,
  ProjectCreateInput,
  ProjectDeleteInput,
  ProjectOpenResult,
  ProjectUpdateInput,
} from "./project";

export type {
  Chapter,
  ChapterCreateInput,
  ChapterSaveResult,
  ChapterSaveStateType,
  ChapterUpdateInput,
  DerivedSyncState,
  Note,
  NoteCreateInput,
  NoteUpdateInput,
  Plot,
  PlotCreateInput,
  PlotUpdateInput,
  Scene,
  SceneCreateInput,
  SceneUpdateInput,
  Synopsis,
  SynopsisCreateInput,
  SynopsisUpdateInput,
} from "./manuscript";

export type {
  Character,
  CharacterAppearanceInput,
  CharacterCreateInput,
  CharacterUpdateInput,
  EntityRelation,
  EntityRelationCreateInput,
  EntityRelationUpdateInput,
  Event,
  EventCreateInput,
  EventUpdateInput,
  Faction,
  FactionCreateInput,
  FactionUpdateInput,
  GraphPluginApplyTemplateInput,
  GraphPluginCatalogItem,
  GraphPluginInstallResult,
  GraphPluginInstallStatus,
  GraphPluginKind,
  GraphPluginManifest,
  GraphPluginTemplateRef,
  GraphTemplateManifest,
  InstalledGraphPlugin,
  RelationKind,
  ReplicaWorldDocumentType,
  ScrapMemo,
  ScrapMemoCreateInput,
  ScrapMemoUpdateInput,
  Term,
  TermAppearanceInput,
  TermCreateInput,
  TermUpdateInput,
  WorldDrawingData,
  WorldDrawingIconType,
  WorldDrawingPath,
  WorldDrawingTool,
  WorldEntity,
  WorldEntityAttributes,
  WorldEntityCreateInput,
  WorldEntitySourceType,
  WorldEntityType,
  WorldEntityUpdateInput,
  WorldEntityUpdatePositionInput,
  WorldGraphCanvasBlock,
  WorldGraphCanvasEdge,
  WorldGraphCanvasEdgeDirection,
  WorldGraphCanvasMemoBlockData,
  WorldGraphCanvasTimelineBlockData,
  WorldGraphData,
  WorldGraphMention,
  WorldGraphMentionsQuery,
  WorldGraphNode,
  WorldMindmapData,
  WorldMindmapEdge,
  WorldMindmapNode,
  WorldMindmapNodeData,
  WorldPlotCard,
  WorldPlotColumn,
  WorldPlotData,
  WorldReplicaDocumentResult,
  WorldReplicaScrapMemosResult,
  WorldScrapMemosData,
  WorldSynopsisData,
  WorldSynopsisStatus,
  WorldTimelineSegment,
  WorldTimelineTrack,
} from "./world";

export type {
  ChapterExportRecord,
  CharacterExportRecord,
  EventExportRecord,
  FactionExportRecord,
  ProjectExportRecord,
  SnapshotExportRecord,
  TermExportRecord,
} from "./export";

export type {
  ChapterSummaryResult,
  ChapterSummaryStatus,
  MemoryChunkBacklink,
  MemoryChunkSearchQuery,
  MemoryChunkSearchResult,
  MemoryEmbeddingStatus,
  MemoryJobStatus,
  MigrationHealth,
  RagQaErrorPayload,
  RagQaEvidence,
  RagQaRequest,
  RagQaResult,
  RagQaRunHandle,
  RagQaStreamPayload,
  SearchIndexStatus,
  SearchQuery,
  SearchResult,
} from "./search";

export type {
  AppBootstrapStatus,
  AppQuitPhase,
  AppQuitPhasePayload,
  AppSettings,
  AppUpdateApplyResult,
  AppUpdateArtifact,
  AppUpdateCheckResult,
  AppUpdateDownloadResult,
  AppUpdateLifecycleStatus,
  AppUpdateRollbackResult,
  AppUpdateState,
  AppUpdateStatus,
  DbRecoveryCheckpoint,
  DbRecoveryFileStatus,
  DbRecoveryResult,
  DbRecoveryStatus,
  DbRecoveryStatusReason,
  EditorSettings,
  EditorTheme,
  EditorUiMode,
  EmbeddingModelStatusView,
  FontFamily,
  FontFamilyPreset,
  FontPreset,
  HfModelFile,
  HfModelSearchResult,
  LlmRuntimeInfo,
  LlmfitInstallStatus,
  LlmfitRecommendation,
  LlmfitResult,
  OllamaConnectionResult,
  RuntimeSupabaseConfig,
  RuntimeSupabaseConfigView,
  ShortcutAction,
  ShortcutMap,
  StartupCheck,
  StartupCheckKey,
  StartupReadiness,
  StartupSettings,
  SyncAuthResult,
  SyncAuthResultReason,
  SyncAuthResultStatus,
  SyncConflictItem,
  SyncConflictSummary,
  SyncConnection,
  SyncEntityBaseline,
  SyncHealth,
  SyncMode,
  SyncPendingProjectDelete,
  SyncProvider,
  SyncRunResult,
  SyncSettings,
  SyncStatus,
  ThemeAccent,
  ThemeContrast,
  ThemeTemperature,
  ThemeTexture,
  WindowBounds,
  WindowMenuBarMode,
  WindowState,
} from "./settings";

export type {
  Snapshot,
  SnapshotCreateInput,
  SnapshotRestoreCandidate,
} from "./snapshot";

// Analysis Types
export type {
  AnalysisRequest,
  AnalysisItem,
  AnalysisContext,
  AnalysisStreamChunk,
  AnalysisResult,
  AnalysisError,
} from "./analysis";
